#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("entry format = ./chatclient ip:port nickname")
    sys.exit()

server = socket.socket(socket.Af_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


inf = (sys.argv[1])
x=inf.split(':')
iPaddress=str(a[0])
port=int(x[1])
nick=str(sys.argv[2])

#used to store values from command line
server.connect((iPaddress, port))
#connects to the server 
firstmsg=server.recv(2048).decode('utf-8')

print(firstmsg)

nick = 'NICK ' + nick
#print('NICK '+nick.encode('utf-8'))

server.sendall(nick.encode('utf-8'))
#senall command sends the info in it as bytes to the server , it sends all the bytes at a time
okmessage=server.recv(2048).decode('utf-8')
print(okmessage)
if okmessage == "OK":
    pass
elif okmessage == "ERR  malformed nick name":
    print('nickname limited to 12 chars')
    print('try valid nickname')
    sys.exit()
    
    



while True:
    socketlist=[sys.stdin, server]
 

    readsockets,writesockets,errorsockets=select.select(socketlist,[],[])
    for sockets in readsockets:
        if sockets == server:
            msg = sockets.recv(2048).decode('utf-8')
            print(msg)
        else:
            msg=sys.stdin.readline()
            msg = 'MSG '+ msg
            if msg == '\n':
                continue
            else:
                server.sendall(msg.encode('utf-8'))
                
server.close()
#above command closes the connection of the socket object
